version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: itesm
      MYSQL_DATABASE: test_database
    ports:
      - "3306:3306"
    restart: always
  express-server:
    depends_on:
      - db
    build: ./Express_Handlebars
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: root
      MYSQL_PASSWORD: itesm
      MYSQL_HOST: db
    ports:
      - "3000:3000"
    restart: on-failure