version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: itesm
      MYSQL_DATABASE: test_database
    restart: always
  express-handlebars:
    build: ./Express_Handlebars
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: always
